/**
 * Created with JetBrains PhpStorm.
 * User: NieHL
 * Date: 12-7-23
 * Time: 下午3:47
 * To change this template use File | Settings | File Templates.
 */
var indicatorFilter = {
    "EndTime":"\/Date(1326384000000+0800)\/",
    "Interface":1,
    "ObjectNames":[
        "FOSSGSN104",
        "FOSSGSN204"
    ],
    "QueryName":null,
    "StartTime":"\/Date(1326297600000+0800)\/",
    "TimeSpan":60,
    "APN":"",
    "BusyHours":"",
    "GroupByType":0,
    "IndicatorDefineOrders":null,
    "IndicatorDefines":[
        {
            "Category":0,
            "DefineId":2,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"Attach成功率",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":3,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"Attach请求重发率",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":4,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"Attach接受重发率",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":5,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"Attach建立时延(有线)",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":9,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"Attach附着失败率（网络原因）",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":10,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"PDP激活请求次数",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":11,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"PDP激活成功率",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":12,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"PDP激活请求重发率",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":16,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"PDP激活失败率（网络原因）",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":17,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"PDP激活请求次数(CMWAP)",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":18,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"PDP激活成功率(CMWAP)",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":19,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"PDP激活请求重发率(CMWAP)",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":20,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"PDP激活时延(CMWAP)",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":22,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"PDP激活成功率（去除用户原因）(CMWAP)",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":23,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"PDP激活失败率（网络原因）(CMWAP)",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":24,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"PDP激活请求次数(CMNET)",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":25,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"PDP激活成功率(CMNET)",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":26,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"PDP激活请求重发率(CMNET)",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":27,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"PDP激活时延(CMNET)",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":29,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"PDP激活成功率(去除用户原因）(CMNET)",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":30,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"PDP激活失败率（网络原因）(CMNET)",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":31,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"PS寻呼次数",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":32,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"PS寻呼成功率",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":33,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"PS寻呼请求重发率",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":34,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"PS寻呼响应时延",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":35,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"PS寻呼无响应比例",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":1,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"Attach请求次数",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":36,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"Flush_ll请求次数",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":37,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"Flush_ll请求成功率",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":38,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"Flush_ll请求时延",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":39,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"Inter_SGSN RAU请求次数",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":40,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"Inter_SGSN RAU成功率",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":41,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"Inter_SGSN RAU请求重发率",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":42,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"Inter_SGSN RAU接受重发率",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":43,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"Inter_SGSN RAU时延(有线)",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":47,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"Intra_SGSN RAU成功率",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":48,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"Intra_SGSN RAU请求重发率",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":49,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"Intra_SGSN RAU接受重发率",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":50,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"Intra_SGSN RAU时延(有线)",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":53,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"RAU请求次数",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":54,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"RAU成功率",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":55,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"RAU请求重发率",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":56,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"RAU接受重发率",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        },
        {
            "Category":0,
            "DefineId":57,
            "DisplayName":null,
            "Expression":null,
            "FormatString":null,
            "IndicatorDefineExtra":null,
            "IndicatorInterface":null,
            "IsMonitor":0,
            "Name":"RAU时延(有线)",
            "SourceTable":null,
            "SubCategory":null,
            "Unit":null
        }
    ],
    "ObjectType":7,
    "ServiceTypeCodes":[
    ],
    "TimeToTime":false,
    "TopN":1000
};

var jsonResult = {
    "ErrorMessage":null,
    "IsCompress":false,
    "Result":'[{"DefineId":0,"ObjectName":"FOSSGSN204","ServiceType":-1,"SubServiceType":-1,"APN":null,"ObjectType":7,"TopN":1000,"Indicators":[{"DefineId":2,"Name":"Attach成功率","Value":0.86568},{"DefineId":5,"Name":"Attach建立时延(有线)","Value":1188.55964},{"DefineId":8,"Name":"Attach附着成功率(去除用户原因)","Value":0.89288},{"DefineId":1,"Name":"Attach请求次数","Value":30770.0},{"DefineId":10,"Name":"PDP激活请求次数","Value":54552.0},{"DefineId":11,"Name":"PDP激活成功率","Value":0.9912},{"DefineId":15,"Name":"PDP激活成功率(去除用户原因）","Value":0.99225},{"DefineId":39,"Name":"Inter_SGSN RAU请求次数","Value":39962.0},{"DefineId":40,"Name":"Inter_SGSN RAU成功率","Value":0.98196},{"DefineId":43,"Name":"Inter_SGSN RAU时延(有线)","Value":836.94852},{"DefineId":46,"Name":"Intra_SGSN RAU请求次数","Value":165707.0},{"DefineId":47,"Name":"Intra_SGSN RAU成功率","Value":0.98264},{"DefineId":50,"Name":"Intra_SGSN RAU时延(有线)","Value":813.6525},{"DefineId":53,"Name":"RAU请求次数","Value":205669.0},{"DefineId":54,"Name":"RAU成功率","Value":0.98251},{"DefineId":57,"Name":"RAU时延(有线)","Value":818.17645}],"BeginTime":"2012-01-12T13:00:00","EndTime":"2012-01-12T14:00:00"},{"DefineId":0,"ObjectName":"FOSSGSN204","ServiceType":-1,"SubServiceType":-1,"APN":null,"ObjectType":7,"TopN":1000,"Indicators":[{"DefineId":2,"Name":"Attach成功率","Value":0.87727},{"DefineId":5,"Name":"Attach建立时延(有线)","Value":1228.47227},{"DefineId":8,"Name":"Attach附着成功率(去除用户原因)","Value":0.90221},{"DefineId":1,"Name":"Attach请求次数","Value":196545.0},{"DefineId":10,"Name":"PDP激活请求次数","Value":339629.0},{"DefineId":11,"Name":"PDP激活成功率","Value":0.99275},{"DefineId":15,"Name":"PDP激活成功率(去除用户原因）","Value":0.99382},{"DefineId":39,"Name":"Inter_SGSN RAU请求次数","Value":246024.0},{"DefineId":40,"Name":"Inter_SGSN RAU成功率","Value":0.98255},{"DefineId":43,"Name":"Inter_SGSN RAU时延(有线)","Value":904.49654},{"DefineId":46,"Name":"Intra_SGSN RAU请求次数","Value":956619.0},{"DefineId":47,"Name":"Intra_SGSN RAU成功率","Value":0.98087},{"DefineId":50,"Name":"Intra_SGSN RAU时延(有线)","Value":859.73083},{"DefineId":53,"Name":"RAU请求次数","Value":1202643.0},{"DefineId":54,"Name":"RAU成功率","Value":0.98121},{"DefineId":57,"Name":"RAU时延(有线)","Value":868.901}],"BeginTime":"2012-01-12T12:00:00","EndTime":"2012-01-12T13:00:00"},{"DefineId":0,"ObjectName":"FOSSGSN204","ServiceType":-1,"SubServiceType":-1,"APN":null,"ObjectType":7,"TopN":1000,"Indicators":[{"DefineId":2,"Name":"Attach成功率","Value":0.87513},{"DefineId":5,"Name":"Attach建立时延(有线)","Value":1245.67347},{"DefineId":8,"Name":"Attach附着成功率(去除用户原因)","Value":0.90461},{"DefineId":1,"Name":"Attach请求次数","Value":231386.0},{"DefineId":10,"Name":"PDP激活请求次数","Value":359224.0},{"DefineId":11,"Name":"PDP激活成功率","Value":0.9929},{"DefineId":15,"Name":"PDP激活成功率(去除用户原因）","Value":0.99493},{"DefineId":39,"Name":"Inter_SGSN RAU请求次数","Value":303453.0},{"DefineId":40,"Name":"Inter_SGSN RAU成功率","Value":0.98349},{"DefineId":43,"Name":"Inter_SGSN RAU时延(有线)","Value":903.75139},{"DefineId":46,"Name":"Intra_SGSN RAU请求次数","Value":1160000.0},{"DefineId":47,"Name":"Intra_SGSN RAU成功率","Value":0.9767},{"DefineId":50,"Name":"Intra_SGSN RAU时延(有线)","Value":902.19586},{"DefineId":53,"Name":"RAU请求次数","Value":1463453.0},{"DefineId":54,"Name":"RAU成功率","Value":0.9781},{"DefineId":57,"Name":"RAU时延(有线)","Value":902.52018}],"BeginTime":"2012-01-12T11:00:00","EndTime":"2012-01-12T12:00:00"},{"DefineId":0,"ObjectName":"FOSSGSN204","ServiceType":-1,"SubServiceType":-1,"APN":null,"ObjectType":7,"TopN":1000,"Indicators":[{"DefineId":2,"Name":"Attach成功率","Value":0.86942},{"DefineId":5,"Name":"Attach建立时延(有线)","Value":1204.00965},{"DefineId":8,"Name":"Attach附着成功率(去除用户原因)","Value":0.89484},{"DefineId":1,"Name":"Attach请求次数","Value":198738.0},{"DefineId":10,"Name":"PDP激活请求次数","Value":404735.0},{"DefineId":11,"Name":"PDP激活成功率","Value":0.99376},{"DefineId":15,"Name":"PDP激活成功率(去除用户原因）","Value":0.9949},{"DefineId":39,"Name":"Inter_SGSN RAU请求次数","Value":298703.0},{"DefineId":40,"Name":"Inter_SGSN RAU成功率","Value":0.98371},{"DefineId":43,"Name":"Inter_SGSN RAU时延(有线)","Value":859.56873},{"DefineId":46,"Name":"Intra_SGSN RAU请求次数","Value":1154663.0},{"DefineId":47,"Name":"Intra_SGSN RAU成功率","Value":0.98109},{"DefineId":50,"Name":"Intra_SGSN RAU时延(有线)","Value":849.08638},{"DefineId":53,"Name":"RAU请求次数","Value":1453366.0},{"DefineId":54,"Name":"RAU成功率","Value":0.98163},{"DefineId":57,"Name":"RAU时延(有线)","Value":851.24532}],"BeginTime":"2012-01-12T10:00:00","EndTime":"2012-01-12T11:00:00"},{"DefineId":0,"ObjectName":"FOSSGSN204","ServiceType":-1,"SubServiceType":-1,"APN":null,"ObjectType":7,"TopN":1000,"Indicators":[{"DefineId":2,"Name":"Attach成功率","Value":0.88009},{"DefineId":5,"Name":"Attach建立时延(有线)","Value":1201.57651},{"DefineId":8,"Name":"Attach附着成功率(去除用户原因)","Value":0.90366},{"DefineId":1,"Name":"Attach请求次数","Value":30423.0},{"DefineId":10,"Name":"PDP激活请求次数","Value":52960.0},{"DefineId":11,"Name":"PDP激活成功率","Value":0.99417},{"DefineId":15,"Name":"PDP激活成功率(去除用户原因）","Value":0.99528},{"DefineId":39,"Name":"Inter_SGSN RAU请求次数","Value":34170.0},{"DefineId":40,"Name":"Inter_SGSN RAU成功率","Value":0.98402},{"DefineId":43,"Name":"Inter_SGSN RAU时延(有线)","Value":831.13172},{"DefineId":46,"Name":"Intra_SGSN RAU请求次数","Value":131400.0},{"DefineId":47,"Name":"Intra_SGSN RAU成功率","Value":0.98132},{"DefineId":50,"Name":"Intra_SGSN RAU时延(有线)","Value":855.86993},{"DefineId":53,"Name":"RAU请求次数","Value":165570.0},{"DefineId":54,"Name":"RAU成功率","Value":0.98187},{"DefineId":57,"Name":"RAU时延(有线)","Value":850.75335}],"BeginTime":"2012-01-12T09:00:00","EndTime":"2012-01-12T10:00:00"}]'
};

var result = [
    {
        "DefineId":0,
        "ObjectName":"FOSSGSN204",
        "ServiceType":-1,
        "SubServiceType":-1,
        "APN":null,
        "ObjectType":7,
        "TopN":1000,
        "Indicators":[
            {
                "DefineId":2,
                "Name":"Attach成功率",
                "Value":0.86568
            },
            {
                "DefineId":5,
                "Name":"Attach建立时延(有线)",
                "Value":1188.55964
            },
            {
                "DefineId":8,
                "Name":"Attach附着成功率(去除用户原因)",
                "Value":0.89288
            },
            {
                "DefineId":1,
                "Name":"Attach请求次数",
                "Value":30770
            },
            {
                "DefineId":10,
                "Name":"PDP激活请求次数",
                "Value":54552
            },
            {
                "DefineId":11,
                "Name":"PDP激活成功率",
                "Value":0.9912
            },
            {
                "DefineId":15,
                "Name":"PDP激活成功率(去除用户原因）",
                "Value":0.99225
            },
            {
                "DefineId":39,
                "Name":"Inter_SGSN RAU请求次数",
                "Value":39962
            },
            {
                "DefineId":40,
                "Name":"Inter_SGSN RAU成功率",
                "Value":0.98196
            },
            {
                "DefineId":43,
                "Name":"Inter_SGSN RAU时延(有线)",
                "Value":836.94852
            },
            {
                "DefineId":46,
                "Name":"Intra_SGSN RAU请求次数",
                "Value":165707
            },
            {
                "DefineId":47,
                "Name":"Intra_SGSN RAU成功率",
                "Value":0.98264
            },
            {
                "DefineId":50,
                "Name":"Intra_SGSN RAU时延(有线)",
                "Value":813.6525
            },
            {
                "DefineId":53,
                "Name":"RAU请求次数",
                "Value":205669
            },
            {
                "DefineId":54,
                "Name":"RAU成功率",
                "Value":0.98251
            },
            {
                "DefineId":57,
                "Name":"RAU时延(有线)",
                "Value":818.17645
            }
        ],
        "BeginTime":"2012-01-12T13:00:00",
        "EndTime":"2012-01-12T14:00:00"
    },
    {
        "DefineId":0,
        "ObjectName":"FOSSGSN204",
        "ServiceType":-1,
        "SubServiceType":-1,
        "APN":null,
        "ObjectType":7,
        "TopN":1000,
        "Indicators":[
            {
                "DefineId":2,
                "Name":"Attach成功率",
                "Value":0.87727
            },
            {
                "DefineId":5,
                "Name":"Attach建立时延(有线)",
                "Value":1228.47227
            },
            {
                "DefineId":8,
                "Name":"Attach附着成功率(去除用户原因)",
                "Value":0.90221
            },
            {
                "DefineId":1,
                "Name":"Attach请求次数",
                "Value":196545
            },
            {
                "DefineId":10,
                "Name":"PDP激活请求次数",
                "Value":339629
            },
            {
                "DefineId":11,
                "Name":"PDP激活成功率",
                "Value":0.99275
            },
            {
                "DefineId":15,
                "Name":"PDP激活成功率(去除用户原因）",
                "Value":0.99382
            },
            {
                "DefineId":39,
                "Name":"Inter_SGSN RAU请求次数",
                "Value":246024
            },
            {
                "DefineId":40,
                "Name":"Inter_SGSN RAU成功率",
                "Value":0.98255
            },
            {
                "DefineId":43,
                "Name":"Inter_SGSN RAU时延(有线)",
                "Value":904.49654
            },
            {
                "DefineId":46,
                "Name":"Intra_SGSN RAU请求次数",
                "Value":956619
            },
            {
                "DefineId":47,
                "Name":"Intra_SGSN RAU成功率",
                "Value":0.98087
            },
            {
                "DefineId":50,
                "Name":"Intra_SGSN RAU时延(有线)",
                "Value":859.73083
            },
            {
                "DefineId":53,
                "Name":"RAU请求次数",
                "Value":1202643
            },
            {
                "DefineId":54,
                "Name":"RAU成功率",
                "Value":0.98121
            },
            {
                "DefineId":57,
                "Name":"RAU时延(有线)",
                "Value":868.901
            }
        ],
        "BeginTime":"2012-01-12T12:00:00",
        "EndTime":"2012-01-12T13:00:00"
    },
    {
        "DefineId":0,
        "ObjectName":"FOSSGSN204",
        "ServiceType":-1,
        "SubServiceType":-1,
        "APN":null,
        "ObjectType":7,
        "TopN":1000,
        "Indicators":[
            {
                "DefineId":2,
                "Name":"Attach成功率",
                "Value":0.87513
            },
            {
                "DefineId":5,
                "Name":"Attach建立时延(有线)",
                "Value":1245.67347
            },
            {
                "DefineId":8,
                "Name":"Attach附着成功率(去除用户原因)",
                "Value":0.90461
            },
            {
                "DefineId":1,
                "Name":"Attach请求次数",
                "Value":231386
            },
            {
                "DefineId":10,
                "Name":"PDP激活请求次数",
                "Value":359224
            },
            {
                "DefineId":11,
                "Name":"PDP激活成功率",
                "Value":0.9929
            },
            {
                "DefineId":15,
                "Name":"PDP激活成功率(去除用户原因）",
                "Value":0.99493
            },
            {
                "DefineId":39,
                "Name":"Inter_SGSN RAU请求次数",
                "Value":303453
            },
            {
                "DefineId":40,
                "Name":"Inter_SGSN RAU成功率",
                "Value":0.98349
            },
            {
                "DefineId":43,
                "Name":"Inter_SGSN RAU时延(有线)",
                "Value":903.75139
            },
            {
                "DefineId":46,
                "Name":"Intra_SGSN RAU请求次数",
                "Value":1160000
            },
            {
                "DefineId":47,
                "Name":"Intra_SGSN RAU成功率",
                "Value":0.9767
            },
            {
                "DefineId":50,
                "Name":"Intra_SGSN RAU时延(有线)",
                "Value":902.19586
            },
            {
                "DefineId":53,
                "Name":"RAU请求次数",
                "Value":1463453
            },
            {
                "DefineId":54,
                "Name":"RAU成功率",
                "Value":0.9781
            },
            {
                "DefineId":57,
                "Name":"RAU时延(有线)",
                "Value":902.52018
            }
        ],
        "BeginTime":"2012-01-12T11:00:00",
        "EndTime":"2012-01-12T12:00:00"
    },
    {
        "DefineId":0,
        "ObjectName":"FOSSGSN204",
        "ServiceType":-1,
        "SubServiceType":-1,
        "APN":null,
        "ObjectType":7,
        "TopN":1000,
        "Indicators":[
            {
                "DefineId":2,
                "Name":"Attach成功率",
                "Value":0.86942
            },
            {
                "DefineId":5,
                "Name":"Attach建立时延(有线)",
                "Value":1204.00965
            },
            {
                "DefineId":8,
                "Name":"Attach附着成功率(去除用户原因)",
                "Value":0.89484
            },
            {
                "DefineId":1,
                "Name":"Attach请求次数",
                "Value":198738
            },
            {
                "DefineId":10,
                "Name":"PDP激活请求次数",
                "Value":404735
            },
            {
                "DefineId":11,
                "Name":"PDP激活成功率",
                "Value":0.99376
            },
            {
                "DefineId":15,
                "Name":"PDP激活成功率(去除用户原因）",
                "Value":0.9949
            },
            {
                "DefineId":39,
                "Name":"Inter_SGSN RAU请求次数",
                "Value":298703
            },
            {
                "DefineId":40,
                "Name":"Inter_SGSN RAU成功率",
                "Value":0.98371
            },
            {
                "DefineId":43,
                "Name":"Inter_SGSN RAU时延(有线)",
                "Value":859.56873
            },
            {
                "DefineId":46,
                "Name":"Intra_SGSN RAU请求次数",
                "Value":1154663
            },
            {
                "DefineId":47,
                "Name":"Intra_SGSN RAU成功率",
                "Value":0.98109
            },
            {
                "DefineId":50,
                "Name":"Intra_SGSN RAU时延(有线)",
                "Value":849.08638
            },
            {
                "DefineId":53,
                "Name":"RAU请求次数",
                "Value":1453366
            },
            {
                "DefineId":54,
                "Name":"RAU成功率",
                "Value":0.98163
            },
            {
                "DefineId":57,
                "Name":"RAU时延(有线)",
                "Value":851.24532
            }
        ],
        "BeginTime":"2012-01-12T10:00:00",
        "EndTime":"2012-01-12T11:00:00"
    },
    {
        "DefineId":0,
        "ObjectName":"FOSSGSN204",
        "ServiceType":-1,
        "SubServiceType":-1,
        "APN":null,
        "ObjectType":7,
        "TopN":1000,
        "Indicators":[
            {
                "DefineId":2,
                "Name":"Attach成功率",
                "Value":0.88009
            },
            {
                "DefineId":5,
                "Name":"Attach建立时延(有线)",
                "Value":1201.57651
            },
            {
                "DefineId":8,
                "Name":"Attach附着成功率(去除用户原因)",
                "Value":0.90366
            },
            {
                "DefineId":1,
                "Name":"Attach请求次数",
                "Value":30423
            },
            {
                "DefineId":10,
                "Name":"PDP激活请求次数",
                "Value":52960
            },
            {
                "DefineId":11,
                "Name":"PDP激活成功率",
                "Value":0.99417
            },
            {
                "DefineId":15,
                "Name":"PDP激活成功率(去除用户原因）",
                "Value":0.99528
            },
            {
                "DefineId":39,
                "Name":"Inter_SGSN RAU请求次数",
                "Value":34170
            },
            {
                "DefineId":40,
                "Name":"Inter_SGSN RAU成功率",
                "Value":0.98402
            },
            {
                "DefineId":43,
                "Name":"Inter_SGSN RAU时延(有线)",
                "Value":831.13172
            },
            {
                "DefineId":46,
                "Name":"Intra_SGSN RAU请求次数",
                "Value":131400
            },
            {
                "DefineId":47,
                "Name":"Intra_SGSN RAU成功率",
                "Value":0.98132
            },
            {
                "DefineId":50,
                "Name":"Intra_SGSN RAU时延(有线)",
                "Value":855.86993
            },
            {
                "DefineId":53,
                "Name":"RAU请求次数",
                "Value":165570
            },
            {
                "DefineId":54,
                "Name":"RAU成功率",
                "Value":0.98187
            },
            {
                "DefineId":57,
                "Name":"RAU时延(有线)",
                "Value":850.75335
            }
        ],
        "BeginTime":"2012-01-12T09:00:00",
        "EndTime":"2012-01-12T10:00:00"
    }
];
